<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title><?php echo $title; ?></title>
        <link rel="stylesheet" type="text/css" href="/game/media/css/style.css">
        
        <script type="text/JavaScript" src="/game/media/js/jquery-2.0.3.min.js"></script>
        <script type="text/JavaScript" src="/game/media/js/gameMane.js"></script>
        
    </head>
    <body>
		<div style="margin-left:30%;" ><h3>Click on any blank box for your move</h3></div>
		<div style="margin-left:30%; width:15%; height:200px; border:1px dotted;">
			
			<div id="board" style="margin:10% 0 0 10%; width:80%; border:1px solid blue;">
			  
			</div>
		
		</div>		
		<div style="margin:10px 0 0 30%; width:10%;" >Players:</div>
		<div style="margin-left:30%; width:10%; background-color:black; color:white" ><h5>Black</h5></div>
		<div style="margin-left:30%; width:10%; background-color:red; color:white" ><h5>Red</h5></div>
		<div style="margin:10px 0 0 30%; width:10%;"><input id="newGame" type="button" value="New Game/Refresh" /></div>
		<div style="margin:10px 0 0 30%; width:10%; font-size:10px;" >[First move from Black player.]</div>
		<div id="errorMsg" style="margin:10px 0 0 30%; width:10%; font-size:12px; color:red;" ></div>

	</body>
</html>

<script type="text/javascript">
$(document).ready(function(){ 

	startGame();

	$('#newGame').click(function() {

		if (window.confirm("Are you sure to leave this game?")) { 
			location.reload();
		}

		return false;
	    
	});
	
});
</script>
